chore(Eslint): add Eslint
STACK-UP-3/warriorz-backend pull request #1
Opened 2020-03-23 13:02 UTC by Francois-MUGOROZI

#171784074 Configure ESLint

#### What does this PR do?
 Having ESLint configured.

#### Description of Task to be completed?
  Having ESLint configured to help check for style violations and flag them.
  Having ESLint configured to use Airbnb convention

#### How should this be manually tested?
After cloning the repo, cd into it, create a <name>.js file
and then try different codes like importing module which does exist and so on.
You will notice warning or error.

#### What are the relevant pivotal tracker stories?
#171784074

2020-03-23 15:53 UTC, irfiacre approved these changes

2020-03-23 15:53 UTC, irfiacre commented on package.json
> +}
please add an empty line

2020-03-24 07:32 UTC, fordarnold reviewed
A minor issue on my side... The `rules:{}` section seems to be having too many rules ignored. Won't this mess things up on during linting.

2020-03-24 08:12 UTC, nkalyesubula requested changes
Well done Francios. A few change requests though,  Please add package-lock.json in .gitignore file, correct the PR title based on the format I shared with you and also make the story ID clickable i.e link it to the PT board

2020-03-24 12:45 UTC, nkalyesubula approved these changes

2020-03-24 12:49 UTC, merged