#171784086 Reset Password via email
STACK-UP-3/warriorz-backend pull request #14
Opened 2020-03-31 16:01 UTC by Francois-MUGOROZI

#### What does this PR do?
Enable user to reset a password when forgotten
#### Description of Task to be completed?
- Create a forgot password endpoint and send reset link to user's email
- Create reset password endpoint to change user password with new one
#### How should this be manually tested?
Give that the user has signed up (refer to signup feature); clone the repo
cd into it and run npm install then npm run dev.
using postman, send forgot password at localhost:5000/api/auth/forgotpassword with email in the body.
If email is yours, you will get a link in your inbox

#### What are the relevant pivotal tracker stories?
[171784086](https://www.pivotaltracker.com/n/projects/2438874/stories/171784086)
#### Screenshots (if appropriate)
![Capture](https://user-images.githubusercontent.com/53614123/78048105-ba038b00-7325-11ea-83bd-225bc2f0af1a.JPG)

2020-03-31 16:59 UTC, benshidanny11 submitted a review, later dismissed
- Good job @Francois-MUGOROZI , 
**Feedbacks**
- I think you are importing files that don't exist in project. 
      Ex: import userService from '../services/userService'; & import sendEmail from '../helpers/email.create'; 
- In model directory of sequelize,  I think is where all models should be, example : User,...

2020-04-01 17:13 UTC, irfiacre requested changes
Nice work @Francois-MUGOROZI.  Just Resolve The hound errors and make sure the tests are running.

2020-04-01 17:13 UTC, irfiacre commented on server/controllers/usercontroller.js
> +    // generate token and send it to email
Remove the comments

2020-04-02 01:07 UTC, kabundege approved these changes
-  A tip on hound errors fix 
 ```just add a comma on the last element in a mentioned objects, it will be solved.```
 - You should squash our commits and remain with one.
 - make sure your tests are running

2020-04-02 11:51 UTC, irfiacre approved these changes

2020-04-02 12:10 UTC, fordarnold approved these changes

2020-04-08 15:09 UTC, bdushimi submitted a review, later dismissed

2020-04-08 15:09 UTC, bdushimi commented on server/controllers/usercontroller.js
> +  static async forgotPassword(req, res) {
@Francois-MUGOROZI sendResetPasswordEmail is more appropriate as the function name.

2020-04-08 15:09 UTC, bdushimi commented on server/controllers/usercontroller.js
> +    const restUrl = `${process.env.RESET_URL}?token=${resetToken}`;
@Francois-MUGOROZI maybe you can change this variable name too to a name that describes what it contains

2020-04-08 15:09 UTC, bdushimi commented on server/controllers/usercontroller.js
> +    sendEmail(html, subj, email);
@Francois-MUGOROZI may you handle the error just in case nodemailer fails to send the email.

2020-04-13 13:04 UTC, merged